FROM alpine:3.7
LABEL maintainer="Bogdan Marian <satrapu@users.noreply.github.com>"

# Ansible releases one should install using pip can be found here: https://github.com/ansible/ansible/releases
ARG ANSIBLE_VERSION="2.4.1.0"
ARG ANSIBLE_PLAYBOOKS_HOME="/opt/ansible-playbooks"

COPY resources/ansible.cfg /etc/ansible/

# The folder containing the Ansible playbooks found on the Docker host
VOLUME [$ANSIBLE_PLAYBOOKS_HOME]
WORKDIR $ANSIBLE_PLAYBOOKS_HOME

RUN apk add --no-cache \
        # Install pip and its dependencies
        build-base \
        libffi-dev \
        python-dev \
        py-cffi \
        py-cryptography \
        py-pip \
    # Install Ansible specific package using pip
    && pip install ansible==$ANSIBLE_VERSION \
    # Avoid a series of warnings
    && echo 'localhost' > /etc/ansible/hosts \
    # Cleanup
    && rm -f /var/cache/apk/* \
    && rm -r /root/.cache