FROM alpine:3.7
LABEL maintainer="Bogdan Marian <satrapu@users.noreply.github.com>"

# Ansible releases one should install on Alpine Linux can be found here: https://pkgs.alpinelinux.org/packages?name=ansible&branch=v3.6
ARG ANSIBLE_VERSION="2.4.1.0-r0"
ARG ANSIBLE_PLAYBOOKS_HOME="/opt/ansible-playbooks"

COPY resources/ansible.cfg /etc/ansible/

# The folder containing the Ansible playbooks found on the Docker host
VOLUME [$ANSIBLE_PLAYBOOKS_HOME]
WORKDIR $ANSIBLE_PLAYBOOKS_HOME

RUN apk add --no-cache ansible=$ANSIBLE_VERSION \
    # Avoid a series of warnings
    && echo 'localhost' > /etc/ansible/hosts \
    # Remove no longer needed files
    && rm -f /var/cache/apk/*